#! /usr/bin/bash

# tacacs
ln -s -r ./raw/intop1-tacacs.tst.md ./docs/guides/tst/intop1-tacacs.tst.md
ln -s -r ./raw/serv-tacacs.tst.md ./docs/guides/tst/serv-tacacs.tst.md
ln -s -r ./raw/conn-ppp04.tst.md ./docs/guides/tst/conn-ppp04.tst.md

# isis
ln -s -r ./raw/intop1-isis01.tst.md ./docs/guides/tst/intop1-isis01.tst.md
ln -s -r ./raw/intop1-isis02.tst.md ./docs/guides/tst/intop1-isis02.tst.md
ln -s -r ./raw/intop1-isis03.tst.md ./docs/guides/tst/intop1-isis03.tst.md
ln -s -r ./raw/intop1-isis04.tst.md ./docs/guides/tst/intop1-isis04.tst.md
ln -s -r ./raw/intop1-isis05.tst.md ./docs/guides/tst/intop1-isis05.tst.md
ln -s -r ./raw/intop1-isis06.tst.md ./docs/guides/tst/intop1-isis06.tst.md
ln -s -r ./raw/intop1-isis07.tst.md ./docs/guides/tst/intop1-isis07.tst.md
ln -s -r ./raw/intop1-isis08.tst.md ./docs/guides/tst/intop1-isis08.tst.md
ln -s -r ./raw/intop1-isis09.tst.md ./docs/guides/tst/intop1-isis09.tst.md
ln -s -r ./raw/intop1-isis10.tst.md ./docs/guides/tst/intop1-isis10.tst.md
ln -s -r ./raw/intop2-isis01.tst.md ./docs/guides/tst/intop2-isis01.tst.md
ln -s -r ./raw/intop2-isis02.tst.md ./docs/guides/tst/intop2-isis02.tst.md
ln -s -r ./raw/intop2-isis03.tst.md ./docs/guides/tst/intop2-isis03.tst.md
ln -s -r ./raw/intop2-isis04.tst.md ./docs/guides/tst/intop2-isis04.tst.md
ln -s -r ./raw/intop2-isis05.tst.md ./docs/guides/tst/intop2-isis05.tst.md
ln -s -r ./raw/intop2-isis06.tst.md ./docs/guides/tst/intop2-isis06.tst.md
ln -s -r ./raw/intop2-isis07.tst.md ./docs/guides/tst/intop2-isis07.tst.md
ln -s -r ./raw/intop2-isis08.tst.md ./docs/guides/tst/intop2-isis08.tst.md
ln -s -r ./raw/intop2-isis09.tst.md ./docs/guides/tst/intop2-isis09.tst.md
ln -s -r ./raw/intop2-isis10.tst.md ./docs/guides/tst/intop2-isis10.tst.md
ln -s -r ./raw/intop9-isis01.tst.md ./docs/guides/tst/intop9-isis01.tst.md
ln -s -r ./raw/intop9-isis02.tst.md ./docs/guides/tst/intop9-isis02.tst.md
ln -s -r ./raw/intop9-isis03.tst.md ./docs/guides/tst/intop9-isis03.tst.md
ln -s -r ./raw/intop9-isis04.tst.md ./docs/guides/tst/intop9-isis04.tst.md
ln -s -r ./raw/intop9-isis05.tst.md ./docs/guides/tst/intop9-isis05.tst.md
ln -s -r ./raw/intop9-isis06.tst.md ./docs/guides/tst/intop9-isis06.tst.md
ln -s -r ./raw/intop9-isis07.tst.md ./docs/guides/tst/intop9-isis07.tst.md
ln -s -r ./raw/rout-isis01.tst.md ./docs/guides/tst/rout-isis01.tst.md
ln -s -r ./raw/rout-isis02.tst.md ./docs/guides/tst/rout-isis02.tst.md
ln -s -r ./raw/rout-isis03.tst.md ./docs/guides/tst/rout-isis03.tst.md
ln -s -r ./raw/rout-isis04.tst.md ./docs/guides/tst/rout-isis04.tst.md
ln -s -r ./raw/rout-isis05.tst.md ./docs/guides/tst/rout-isis05.tst.md
ln -s -r ./raw/rout-isis06.tst.md ./docs/guides/tst/rout-isis06.tst.md
ln -s -r ./raw/rout-isis07.tst.md ./docs/guides/tst/rout-isis07.tst.md
ln -s -r ./raw/rout-isis08.tst.md ./docs/guides/tst/rout-isis08.tst.md
ln -s -r ./raw/rout-isis09.tst.md ./docs/guides/tst/rout-isis09.tst.md
ln -s -r ./raw/rout-isis10.tst.md ./docs/guides/tst/rout-isis10.tst.md
ln -s -r ./raw/rout-isis11.tst.md ./docs/guides/tst/rout-isis11.tst.md
ln -s -r ./raw/rout-isis12.tst.md ./docs/guides/tst/rout-isis12.tst.md
ln -s -r ./raw/rout-isis13.tst.md ./docs/guides/tst/rout-isis13.tst.md
ln -s -r ./raw/rout-isis14.tst.md ./docs/guides/tst/rout-isis14.tst.md
ln -s -r ./raw/rout-isis15.tst.md ./docs/guides/tst/rout-isis15.tst.md
ln -s -r ./raw/rout-isis16.tst.md ./docs/guides/tst/rout-isis16.tst.md
ln -s -r ./raw/rout-isis17.tst.md ./docs/guides/tst/rout-isis17.tst.md
ln -s -r ./raw/rout-isis18.tst.md ./docs/guides/tst/rout-isis18.tst.md
ln -s -r ./raw/rout-isis19.tst.md ./docs/guides/tst/rout-isis19.tst.md
ln -s -r ./raw/rout-isis20.tst.md ./docs/guides/tst/rout-isis20.tst.md
ln -s -r ./raw/rout-isis21.tst.md ./docs/guides/tst/rout-isis21.tst.md
ln -s -r ./raw/rout-isis22.tst.md ./docs/guides/tst/rout-isis22.tst.md
ln -s -r ./raw/rout-isis23.tst.md ./docs/guides/tst/rout-isis23.tst.md
ln -s -r ./raw/rout-isis24.tst.md ./docs/guides/tst/rout-isis24.tst.md
ln -s -r ./raw/rout-isis25.tst.md ./docs/guides/tst/rout-isis25.tst.md
ln -s -r ./raw/rout-isis26.tst.md ./docs/guides/tst/rout-isis26.tst.md
ln -s -r ./raw/rout-isis27.tst.md ./docs/guides/tst/rout-isis27.tst.md
ln -s -r ./raw/rout-isis28.tst.md ./docs/guides/tst/rout-isis28.tst.md
ln -s -r ./raw/rout-isis29.tst.md ./docs/guides/tst/rout-isis29.tst.md
ln -s -r ./raw/rout-isis30.tst.md ./docs/guides/tst/rout-isis30.tst.md
ln -s -r ./raw/rout-isis31.tst.md ./docs/guides/tst/rout-isis31.tst.md
ln -s -r ./raw/rout-isis32.tst.md ./docs/guides/tst/rout-isis32.tst.md
ln -s -r ./raw/rout-isis33.tst.md ./docs/guides/tst/rout-isis33.tst.md
ln -s -r ./raw/rout-isis34.tst.md ./docs/guides/tst/rout-isis34.tst.md
ln -s -r ./raw/rout-isis35.tst.md ./docs/guides/tst/rout-isis35.tst.md
ln -s -r ./raw/rout-isis36.tst.md ./docs/guides/tst/rout-isis36.tst.md
ln -s -r ./raw/rout-isis37.tst.md ./docs/guides/tst/rout-isis37.tst.md
ln -s -r ./raw/rout-isis38.tst.md ./docs/guides/tst/rout-isis38.tst.md
ln -s -r ./raw/rout-isis39.tst.md ./docs/guides/tst/rout-isis39.tst.md
ln -s -r ./raw/rout-isis40.tst.md ./docs/guides/tst/rout-isis40.tst.md
ln -s -r ./raw/rout-isis41.tst.md ./docs/guides/tst/rout-isis41.tst.md
ln -s -r ./raw/rout-isis42.tst.md ./docs/guides/tst/rout-isis42.tst.md
ln -s -r ./raw/rout-isis43.tst.md ./docs/guides/tst/rout-isis43.tst.md
ln -s -r ./raw/rout-isis44.tst.md ./docs/guides/tst/rout-isis44.tst.md
ln -s -r ./raw/rout-isis45.tst.md ./docs/guides/tst/rout-isis45.tst.md
ln -s -r ./raw/rout-isis46.tst.md ./docs/guides/tst/rout-isis46.tst.md
ln -s -r ./raw/rout-isis47.tst.md ./docs/guides/tst/rout-isis47.tst.md
ln -s -r ./raw/rout-isis48.tst.md ./docs/guides/tst/rout-isis48.tst.md
ln -s -r ./raw/rout-isis49.tst.md ./docs/guides/tst/rout-isis49.tst.md
ln -s -r ./raw/rout-isis50.tst.md ./docs/guides/tst/rout-isis50.tst.md
ln -s -r ./raw/rout-isis51.tst.md ./docs/guides/tst/rout-isis51.tst.md
ln -s -r ./raw/rout-isis52.tst.md ./docs/guides/tst/rout-isis52.tst.md
ln -s -r ./raw/rout-isis53.tst.md ./docs/guides/tst/rout-isis53.tst.md
ln -s -r ./raw/rout-redist01.tst.md ./docs/guides/tst/rout-redist01.tst.md

# ospf
ln -s -r ./raw/intop1-ospf01.tst.md ./docs/guides/tst/intop1-ospf01.tst.md
ln -s -r ./raw/intop1-ospf02.tst.md ./docs/guides/tst/intop1-ospf02.tst.md
ln -s -r ./raw/intop1-ospf03.tst.md ./docs/guides/tst/intop1-ospf03.tst.md
ln -s -r ./raw/intop1-ospf04.tst.md ./docs/guides/tst/intop1-ospf04.tst.md
ln -s -r ./raw/intop1-ospf05.tst.md ./docs/guides/tst/intop1-ospf05.tst.md
ln -s -r ./raw/intop1-ospf06.tst.md ./docs/guides/tst/intop1-ospf06.tst.md
ln -s -r ./raw/intop1-ospf07.tst.md ./docs/guides/tst/intop1-ospf07.tst.md
ln -s -r ./raw/intop1-ospf08.tst.md ./docs/guides/tst/intop1-ospf08.tst.md
ln -s -r ./raw/intop1-ospf09.tst.md ./docs/guides/tst/intop1-ospf09.tst.md
ln -s -r ./raw/intop1-ospf10.tst.md ./docs/guides/tst/intop1-ospf10.tst.md
ln -s -r ./raw/intop1-ospf11.tst.md ./docs/guides/tst/intop1-ospf11.tst.md
ln -s -r ./raw/intop2-ospf01.tst.md ./docs/guides/tst/intop2-ospf01.tst.md
ln -s -r ./raw/intop2-ospf02.tst.md ./docs/guides/tst/intop2-ospf02.tst.md
ln -s -r ./raw/intop2-ospf03.tst.md ./docs/guides/tst/intop2-ospf03.tst.md
ln -s -r ./raw/intop2-ospf04.tst.md ./docs/guides/tst/intop2-ospf04.tst.md
ln -s -r ./raw/intop2-ospf05.tst.md ./docs/guides/tst/intop2-ospf05.tst.md
ln -s -r ./raw/intop2-ospf06.tst.md ./docs/guides/tst/intop2-ospf06.tst.md
ln -s -r ./raw/intop2-ospf07.tst.md ./docs/guides/tst/intop2-ospf07.tst.md
ln -s -r ./raw/intop2-ospf08.tst.md ./docs/guides/tst/intop2-ospf08.tst.md
ln -s -r ./raw/intop2-ospf09.tst.md ./docs/guides/tst/intop2-ospf09.tst.md
ln -s -r ./raw/intop2-ospf10.tst.md ./docs/guides/tst/intop2-ospf10.tst.md
ln -s -r ./raw/intop2-ospf11.tst.md ./docs/guides/tst/intop2-ospf11.tst.md
ln -s -r ./raw/intop9-ospf01.tst.md ./docs/guides/tst/intop9-ospf01.tst.md
ln -s -r ./raw/intop9-ospf02.tst.md ./docs/guides/tst/intop9-ospf02.tst.md
ln -s -r ./raw/intop9-ospf03.tst.md ./docs/guides/tst/intop9-ospf03.tst.md
ln -s -r ./raw/intop9-ospf04.tst.md ./docs/guides/tst/intop9-ospf04.tst.md
ln -s -r ./raw/intop9-ospf05.tst.md ./docs/guides/tst/intop9-ospf05.tst.md
ln -s -r ./raw/intop9-ospf06.tst.md ./docs/guides/tst/intop9-ospf06.tst.md
ln -s -r ./raw/intop9-ospf07.tst.md ./docs/guides/tst/intop9-ospf07.tst.md
ln -s -r ./raw/intop9-ospf08.tst.md ./docs/guides/tst/intop9-ospf08.tst.md
ln -s -r ./raw/intop9-ospf09.tst.md ./docs/guides/tst/intop9-ospf09.tst.md
ln -s -r ./raw/intop9-ospf10.tst.md ./docs/guides/tst/intop9-ospf10.tst.md
ln -s -r ./raw/rout-ospf01.tst.md ./docs/guides/tst/rout-ospf01.tst.md
ln -s -r ./raw/rout-ospf02.tst.md ./docs/guides/tst/rout-ospf02.tst.md
ln -s -r ./raw/rout-ospf03.tst.md ./docs/guides/tst/rout-ospf03.tst.md
ln -s -r ./raw/rout-ospf04.tst.md ./docs/guides/tst/rout-ospf04.tst.md
ln -s -r ./raw/rout-ospf05.tst.md ./docs/guides/tst/rout-ospf05.tst.md
ln -s -r ./raw/rout-ospf06.tst.md ./docs/guides/tst/rout-ospf06.tst.md
ln -s -r ./raw/rout-ospf07.tst.md ./docs/guides/tst/rout-ospf07.tst.md
ln -s -r ./raw/rout-ospf08.tst.md ./docs/guides/tst/rout-ospf08.tst.md
ln -s -r ./raw/rout-ospf09.tst.md ./docs/guides/tst/rout-ospf09.tst.md
ln -s -r ./raw/rout-ospf10.tst.md ./docs/guides/tst/rout-ospf10.tst.md
ln -s -r ./raw/rout-ospf11.tst.md ./docs/guides/tst/rout-ospf11.tst.md
ln -s -r ./raw/rout-ospf12.tst.md ./docs/guides/tst/rout-ospf12.tst.md
ln -s -r ./raw/rout-ospf13.tst.md ./docs/guides/tst/rout-ospf13.tst.md
ln -s -r ./raw/rout-ospf14.tst.md ./docs/guides/tst/rout-ospf14.tst.md
ln -s -r ./raw/rout-ospf15.tst.md ./docs/guides/tst/rout-ospf15.tst.md
ln -s -r ./raw/rout-ospf16.tst.md ./docs/guides/tst/rout-ospf16.tst.md
ln -s -r ./raw/rout-ospf17.tst.md ./docs/guides/tst/rout-ospf17.tst.md
ln -s -r ./raw/rout-ospf18.tst.md ./docs/guides/tst/rout-ospf18.tst.md
ln -s -r ./raw/rout-ospf19.tst.md ./docs/guides/tst/rout-ospf19.tst.md
ln -s -r ./raw/rout-ospf20.tst.md ./docs/guides/tst/rout-ospf20.tst.md
ln -s -r ./raw/rout-ospf21.tst.md ./docs/guides/tst/rout-ospf21.tst.md
ln -s -r ./raw/rout-ospf22.tst.md ./docs/guides/tst/rout-ospf22.tst.md
ln -s -r ./raw/rout-ospf23.tst.md ./docs/guides/tst/rout-ospf23.tst.md
ln -s -r ./raw/rout-ospf24.tst.md ./docs/guides/tst/rout-ospf24.tst.md
ln -s -r ./raw/rout-ospf25.tst.md ./docs/guides/tst/rout-ospf25.tst.md
ln -s -r ./raw/rout-ospf26.tst.md ./docs/guides/tst/rout-ospf26.tst.md
ln -s -r ./raw/rout-ospf27.tst.md ./docs/guides/tst/rout-ospf27.tst.md
ln -s -r ./raw/rout-ospf28.tst.md ./docs/guides/tst/rout-ospf28.tst.md
ln -s -r ./raw/rout-ospf29.tst.md ./docs/guides/tst/rout-ospf29.tst.md
ln -s -r ./raw/rout-ospf30.tst.md ./docs/guides/tst/rout-ospf30.tst.md
ln -s -r ./raw/rout-ospf31.tst.md ./docs/guides/tst/rout-ospf31.tst.md
ln -s -r ./raw/rout-ospf32.tst.md ./docs/guides/tst/rout-ospf32.tst.md
ln -s -r ./raw/rout-ospf33.tst.md ./docs/guides/tst/rout-ospf33.tst.md
ln -s -r ./raw/rout-ospf34.tst.md ./docs/guides/tst/rout-ospf34.tst.md
ln -s -r ./raw/rout-ospf35.tst.md ./docs/guides/tst/rout-ospf35.tst.md
ln -s -r ./raw/rout-ospf36.tst.md ./docs/guides/tst/rout-ospf36.tst.md
ln -s -r ./raw/rout-ospf37.tst.md ./docs/guides/tst/rout-ospf37.tst.md
ln -s -r ./raw/rout-ospf38.tst.md ./docs/guides/tst/rout-ospf38.tst.md
ln -s -r ./raw/rout-ospf39.tst.md ./docs/guides/tst/rout-ospf39.tst.md
ln -s -r ./raw/rout-ospf40.tst.md ./docs/guides/tst/rout-ospf40.tst.md
ln -s -r ./raw/rout-redist02.tst.md ./docs/guides/tst/rout-redist02.tst.md

# bgp
ln -s -r ./raw/intop1-bgp01.tst.md ./docs/guides/tst/intop1-bgp01.tst.md
ln -s -r ./raw/intop1-bgp02.tst.md ./docs/guides/tst/intop1-bgp02.tst.md
ln -s -r ./raw/intop1-bgp03.tst.md ./docs/guides/tst/intop1-bgp03.tst.md
ln -s -r ./raw/intop1-bgp04.tst.md ./docs/guides/tst/intop1-bgp04.tst.md
ln -s -r ./raw/intop1-bgp05.tst.md ./docs/guides/tst/intop1-bgp05.tst.md
ln -s -r ./raw/intop1-bgp06.tst.md ./docs/guides/tst/intop1-bgp06.tst.md
ln -s -r ./raw/intop1-bgp07.tst.md ./docs/guides/tst/intop1-bgp07.tst.md
ln -s -r ./raw/intop1-bgp08.tst.md ./docs/guides/tst/intop1-bgp08.tst.md
ln -s -r ./raw/intop1-bgp09.tst.md ./docs/guides/tst/intop1-bgp09.tst.md
ln -s -r ./raw/intop1-bgp10.tst.md ./docs/guides/tst/intop1-bgp10.tst.md
ln -s -r ./raw/intop1-bgp11.tst.md ./docs/guides/tst/intop1-bgp11.tst.md
ln -s -r ./raw/intop1-bgp12.tst.md ./docs/guides/tst/intop1-bgp12.tst.md
ln -s -r ./raw/intop1-bgp13.tst.md ./docs/guides/tst/intop1-bgp13.tst.md
ln -s -r ./raw/intop1-bgp14.tst.md ./docs/guides/tst/intop1-bgp14.tst.md
ln -s -r ./raw/intop1-bgp15.tst.md ./docs/guides/tst/intop1-bgp15.tst.md
ln -s -r ./raw/intop1-bgp16.tst.md ./docs/guides/tst/intop1-bgp16.tst.md
ln -s -r ./raw/intop1-bgp17.tst.md ./docs/guides/tst/intop1-bgp17.tst.md
ln -s -r ./raw/intop1-bgp18.tst.md ./docs/guides/tst/intop1-bgp18.tst.md
ln -s -r ./raw/intop2-bgp01.tst.md ./docs/guides/tst/intop2-bgp01.tst.md
ln -s -r ./raw/intop2-bgp02.tst.md ./docs/guides/tst/intop2-bgp02.tst.md
ln -s -r ./raw/intop2-bgp03.tst.md ./docs/guides/tst/intop2-bgp03.tst.md
ln -s -r ./raw/intop2-bgp04.tst.md ./docs/guides/tst/intop2-bgp04.tst.md
ln -s -r ./raw/intop2-bgp05.tst.md ./docs/guides/tst/intop2-bgp05.tst.md
ln -s -r ./raw/intop2-bgp06.tst.md ./docs/guides/tst/intop2-bgp06.tst.md
ln -s -r ./raw/intop2-bgp07.tst.md ./docs/guides/tst/intop2-bgp07.tst.md
ln -s -r ./raw/intop2-bgp08.tst.md ./docs/guides/tst/intop2-bgp08.tst.md
ln -s -r ./raw/intop2-bgp09.tst.md ./docs/guides/tst/intop2-bgp09.tst.md
ln -s -r ./raw/intop2-bgp10.tst.md ./docs/guides/tst/intop2-bgp10.tst.md
ln -s -r ./raw/intop2-bgp11.tst.md ./docs/guides/tst/intop2-bgp11.tst.md
ln -s -r ./raw/intop2-bgp12.tst.md ./docs/guides/tst/intop2-bgp12.tst.md
ln -s -r ./raw/intop2-bgp13.tst.md ./docs/guides/tst/intop2-bgp13.tst.md
ln -s -r ./raw/intop2-bgp14.tst.md ./docs/guides/tst/intop2-bgp14.tst.md
ln -s -r ./raw/intop2-bgp15.tst.md ./docs/guides/tst/intop2-bgp15.tst.md
ln -s -r ./raw/intop2-bgp16.tst.md ./docs/guides/tst/intop2-bgp16.tst.md
ln -s -r ./raw/intop2-bgp17.tst.md ./docs/guides/tst/intop2-bgp17.tst.md
ln -s -r ./raw/intop2-bgp18.tst.md ./docs/guides/tst/intop2-bgp18.tst.md
ln -s -r ./raw/intop2-bgp19.tst.md ./docs/guides/tst/intop2-bgp19.tst.md
ln -s -r ./raw/intop2-bgp20.tst.md ./docs/guides/tst/intop2-bgp20.tst.md
ln -s -r ./raw/intop2-bgp21.tst.md ./docs/guides/tst/intop2-bgp21.tst.md
ln -s -r ./raw/intop2-bgp22.tst.md ./docs/guides/tst/intop2-bgp22.tst.md
ln -s -r ./raw/intop9-bgp01.tst.md ./docs/guides/tst/intop9-bgp01.tst.md
ln -s -r ./raw/intop9-bgp02.tst.md ./docs/guides/tst/intop9-bgp02.tst.md
ln -s -r ./raw/intop9-bgp03.tst.md ./docs/guides/tst/intop9-bgp03.tst.md
ln -s -r ./raw/intop9-bgp04.tst.md ./docs/guides/tst/intop9-bgp04.tst.md
ln -s -r ./raw/intop9-bgp05.tst.md ./docs/guides/tst/intop9-bgp05.tst.md
ln -s -r ./raw/intop9-bgp06.tst.md ./docs/guides/tst/intop9-bgp06.tst.md
ln -s -r ./raw/intop9-bgp07.tst.md ./docs/guides/tst/intop9-bgp07.tst.md
ln -s -r ./raw/intop9-bgp08.tst.md ./docs/guides/tst/intop9-bgp08.tst.md
ln -s -r ./raw/intop9-bgp09.tst.md ./docs/guides/tst/intop9-bgp09.tst.md
ln -s -r ./raw/intop9-bgp10.tst.md ./docs/guides/tst/intop9-bgp10.tst.md
ln -s -r ./raw/intop9-bgp11.tst.md ./docs/guides/tst/intop9-bgp11.tst.md
ln -s -r ./raw/intop9-bgp12.tst.md ./docs/guides/tst/intop9-bgp12.tst.md
ln -s -r ./raw/intop9-bgp13.tst.md ./docs/guides/tst/intop9-bgp13.tst.md
ln -s -r ./raw/intop9-bgp14.tst.md ./docs/guides/tst/intop9-bgp14.tst.md
ln -s -r ./raw/intop9-bgp15.tst.md ./docs/guides/tst/intop9-bgp15.tst.md
ln -s -r ./raw/intop9-bgp16.tst.md ./docs/guides/tst/intop9-bgp16.tst.md
ln -s -r ./raw/intop9-bgp17.tst.md ./docs/guides/tst/intop9-bgp17.tst.md
ln -s -r ./raw/rout-bgp001.tst.md ./docs/guides/tst/rout-bgp001.tst.md
ln -s -r ./raw/rout-bgp002.tst.md ./docs/guides/tst/rout-bgp002.tst.md
ln -s -r ./raw/rout-bgp003.tst.md ./docs/guides/tst/rout-bgp003.tst.md
ln -s -r ./raw/rout-bgp004.tst.md ./docs/guides/tst/rout-bgp004.tst.md
ln -s -r ./raw/rout-bgp005.tst.md ./docs/guides/tst/rout-bgp005.tst.md
ln -s -r ./raw/rout-bgp006.tst.md ./docs/guides/tst/rout-bgp006.tst.md
ln -s -r ./raw/rout-bgp007.tst.md ./docs/guides/tst/rout-bgp007.tst.md
ln -s -r ./raw/rout-bgp008.tst.md ./docs/guides/tst/rout-bgp008.tst.md
ln -s -r ./raw/rout-bgp009.tst.md ./docs/guides/tst/rout-bgp009.tst.md
ln -s -r ./raw/rout-bgp010.tst.md ./docs/guides/tst/rout-bgp010.tst.md
ln -s -r ./raw/rout-bgp011.tst.md ./docs/guides/tst/rout-bgp011.tst.md
ln -s -r ./raw/rout-bgp012.tst.md ./docs/guides/tst/rout-bgp012.tst.md
ln -s -r ./raw/rout-bgp013.tst.md ./docs/guides/tst/rout-bgp013.tst.md
ln -s -r ./raw/rout-bgp014.tst.md ./docs/guides/tst/rout-bgp014.tst.md
ln -s -r ./raw/rout-bgp015.tst.md ./docs/guides/tst/rout-bgp015.tst.md
ln -s -r ./raw/rout-bgp016.tst.md ./docs/guides/tst/rout-bgp016.tst.md
ln -s -r ./raw/rout-bgp017.tst.md ./docs/guides/tst/rout-bgp017.tst.md
ln -s -r ./raw/rout-bgp018.tst.md ./docs/guides/tst/rout-bgp018.tst.md
ln -s -r ./raw/rout-bgp019.tst.md ./docs/guides/tst/rout-bgp019.tst.md
ln -s -r ./raw/rout-bgp020.tst.md ./docs/guides/tst/rout-bgp020.tst.md
ln -s -r ./raw/rout-bgp021.tst.md ./docs/guides/tst/rout-bgp021.tst.md
ln -s -r ./raw/rout-bgp022.tst.md ./docs/guides/tst/rout-bgp022.tst.md
ln -s -r ./raw/rout-bgp023.tst.md ./docs/guides/tst/rout-bgp023.tst.md
ln -s -r ./raw/rout-bgp024.tst.md ./docs/guides/tst/rout-bgp024.tst.md
ln -s -r ./raw/rout-bgp025.tst.md ./docs/guides/tst/rout-bgp025.tst.md
ln -s -r ./raw/rout-bgp026.tst.md ./docs/guides/tst/rout-bgp026.tst.md
ln -s -r ./raw/rout-bgp027.tst.md ./docs/guides/tst/rout-bgp027.tst.md
ln -s -r ./raw/rout-bgp028.tst.md ./docs/guides/tst/rout-bgp028.tst.md
ln -s -r ./raw/rout-bgp029.tst.md ./docs/guides/tst/rout-bgp029.tst.md
ln -s -r ./raw/rout-bgp030.tst.md ./docs/guides/tst/rout-bgp030.tst.md
ln -s -r ./raw/rout-bgp031.tst.md ./docs/guides/tst/rout-bgp031.tst.md
ln -s -r ./raw/rout-bgp032.tst.md ./docs/guides/tst/rout-bgp032.tst.md
ln -s -r ./raw/rout-bgp033.tst.md ./docs/guides/tst/rout-bgp033.tst.md
ln -s -r ./raw/rout-bgp034.tst.md ./docs/guides/tst/rout-bgp034.tst.md
ln -s -r ./raw/rout-bgp035.tst.md ./docs/guides/tst/rout-bgp035.tst.md
ln -s -r ./raw/rout-bgp036.tst.md ./docs/guides/tst/rout-bgp036.tst.md
ln -s -r ./raw/rout-bgp037.tst.md ./docs/guides/tst/rout-bgp037.tst.md
ln -s -r ./raw/rout-bgp038.tst.md ./docs/guides/tst/rout-bgp038.tst.md
ln -s -r ./raw/rout-bgp039.tst.md ./docs/guides/tst/rout-bgp039.tst.md
ln -s -r ./raw/rout-bgp040.tst.md ./docs/guides/tst/rout-bgp040.tst.md
ln -s -r ./raw/rout-bgp041.tst.md ./docs/guides/tst/rout-bgp041.tst.md
ln -s -r ./raw/rout-bgp042.tst.md ./docs/guides/tst/rout-bgp042.tst.md
ln -s -r ./raw/rout-bgp043.tst.md ./docs/guides/tst/rout-bgp043.tst.md
ln -s -r ./raw/rout-bgp044.tst.md ./docs/guides/tst/rout-bgp044.tst.md
ln -s -r ./raw/rout-bgp045.tst.md ./docs/guides/tst/rout-bgp045.tst.md
ln -s -r ./raw/rout-bgp046.tst.md ./docs/guides/tst/rout-bgp046.tst.md
ln -s -r ./raw/rout-bgp047.tst.md ./docs/guides/tst/rout-bgp047.tst.md
ln -s -r ./raw/rout-bgp048.tst.md ./docs/guides/tst/rout-bgp048.tst.md
ln -s -r ./raw/rout-bgp049.tst.md ./docs/guides/tst/rout-bgp049.tst.md
ln -s -r ./raw/rout-bgp050.tst.md ./docs/guides/tst/rout-bgp050.tst.md
ln -s -r ./raw/rout-bgp051.tst.md ./docs/guides/tst/rout-bgp051.tst.md
ln -s -r ./raw/rout-bgp052.tst.md ./docs/guides/tst/rout-bgp052.tst.md
ln -s -r ./raw/rout-bgp053.tst.md ./docs/guides/tst/rout-bgp053.tst.md
ln -s -r ./raw/rout-bgp054.tst.md ./docs/guides/tst/rout-bgp054.tst.md
ln -s -r ./raw/rout-bgp055.tst.md ./docs/guides/tst/rout-bgp055.tst.md
ln -s -r ./raw/rout-bgp056.tst.md ./docs/guides/tst/rout-bgp056.tst.md
ln -s -r ./raw/rout-bgp057.tst.md ./docs/guides/tst/rout-bgp057.tst.md
ln -s -r ./raw/rout-bgp058.tst.md ./docs/guides/tst/rout-bgp058.tst.md
ln -s -r ./raw/rout-bgp059.tst.md ./docs/guides/tst/rout-bgp059.tst.md
ln -s -r ./raw/rout-bgp060.tst.md ./docs/guides/tst/rout-bgp060.tst.md
ln -s -r ./raw/rout-bgp061.tst.md ./docs/guides/tst/rout-bgp061.tst.md
ln -s -r ./raw/rout-bgp062.tst.md ./docs/guides/tst/rout-bgp062.tst.md
ln -s -r ./raw/rout-bgp063.tst.md ./docs/guides/tst/rout-bgp063.tst.md
ln -s -r ./raw/rout-bgp064.tst.md ./docs/guides/tst/rout-bgp064.tst.md
ln -s -r ./raw/rout-bgp065.tst.md ./docs/guides/tst/rout-bgp065.tst.md
ln -s -r ./raw/rout-bgp066.tst.md ./docs/guides/tst/rout-bgp066.tst.md
ln -s -r ./raw/rout-bgp067.tst.md ./docs/guides/tst/rout-bgp067.tst.md
ln -s -r ./raw/rout-bgp068.tst.md ./docs/guides/tst/rout-bgp068.tst.md
ln -s -r ./raw/rout-bgp069.tst.md ./docs/guides/tst/rout-bgp069.tst.md
ln -s -r ./raw/rout-bgp070.tst.md ./docs/guides/tst/rout-bgp070.tst.md
ln -s -r ./raw/rout-bgp071.tst.md ./docs/guides/tst/rout-bgp071.tst.md
ln -s -r ./raw/rout-bgp072.tst.md ./docs/guides/tst/rout-bgp072.tst.md
ln -s -r ./raw/rout-bgp073.tst.md ./docs/guides/tst/rout-bgp073.tst.md
ln -s -r ./raw/rout-bgp074.tst.md ./docs/guides/tst/rout-bgp074.tst.md
ln -s -r ./raw/rout-bgp075.tst.md ./docs/guides/tst/rout-bgp075.tst.md
ln -s -r ./raw/rout-bgp076.tst.md ./docs/guides/tst/rout-bgp076.tst.md
ln -s -r ./raw/rout-bgp077.tst.md ./docs/guides/tst/rout-bgp077.tst.md
ln -s -r ./raw/rout-bgp078.tst.md ./docs/guides/tst/rout-bgp078.tst.md
ln -s -r ./raw/rout-bgp079.tst.md ./docs/guides/tst/rout-bgp079.tst.md
ln -s -r ./raw/rout-bgp080.tst.md ./docs/guides/tst/rout-bgp080.tst.md
ln -s -r ./raw/rout-bgp081.tst.md ./docs/guides/tst/rout-bgp081.tst.md
ln -s -r ./raw/rout-bgp082.tst.md ./docs/guides/tst/rout-bgp082.tst.md
ln -s -r ./raw/rout-bgp083.tst.md ./docs/guides/tst/rout-bgp083.tst.md
ln -s -r ./raw/rout-bgp084.tst.md ./docs/guides/tst/rout-bgp084.tst.md
ln -s -r ./raw/rout-bgp085.tst.md ./docs/guides/tst/rout-bgp085.tst.md
ln -s -r ./raw/rout-bgp086.tst.md ./docs/guides/tst/rout-bgp086.tst.md
ln -s -r ./raw/rout-bgp087.tst.md ./docs/guides/tst/rout-bgp087.tst.md
ln -s -r ./raw/rout-bgp088.tst.md ./docs/guides/tst/rout-bgp088.tst.md
ln -s -r ./raw/rout-bgp089.tst.md ./docs/guides/tst/rout-bgp089.tst.md
ln -s -r ./raw/rout-bgp090.tst.md ./docs/guides/tst/rout-bgp090.tst.md
ln -s -r ./raw/rout-bgp091.tst.md ./docs/guides/tst/rout-bgp091.tst.md
ln -s -r ./raw/rout-bgp092.tst.md ./docs/guides/tst/rout-bgp092.tst.md
ln -s -r ./raw/rout-bgp093.tst.md ./docs/guides/tst/rout-bgp093.tst.md
ln -s -r ./raw/rout-bgp094.tst.md ./docs/guides/tst/rout-bgp094.tst.md
ln -s -r ./raw/rout-bgp095.tst.md ./docs/guides/tst/rout-bgp095.tst.md
ln -s -r ./raw/rout-bgp096.tst.md ./docs/guides/tst/rout-bgp096.tst.md
ln -s -r ./raw/rout-bgp097.tst.md ./docs/guides/tst/rout-bgp097.tst.md
ln -s -r ./raw/rout-bgp098.tst.md ./docs/guides/tst/rout-bgp098.tst.md
ln -s -r ./raw/rout-bgp099.tst.md ./docs/guides/tst/rout-bgp099.tst.md
ln -s -r ./raw/rout-bgp100.tst.md ./docs/guides/tst/rout-bgp100.tst.md
ln -s -r ./raw/rout-bgp101.tst.md ./docs/guides/tst/rout-bgp101.tst.md
ln -s -r ./raw/rout-bgp102.tst.md ./docs/guides/tst/rout-bgp102.tst.md
ln -s -r ./raw/rout-bgp103.tst.md ./docs/guides/tst/rout-bgp103.tst.md
ln -s -r ./raw/rout-bgp104.tst.md ./docs/guides/tst/rout-bgp104.tst.md
ln -s -r ./raw/rout-bgp105.tst.md ./docs/guides/tst/rout-bgp105.tst.md
ln -s -r ./raw/rout-bgp106.tst.md ./docs/guides/tst/rout-bgp106.tst.md
ln -s -r ./raw/rout-bgp107.tst.md ./docs/guides/tst/rout-bgp107.tst.md
ln -s -r ./raw/rout-bgp108.tst.md ./docs/guides/tst/rout-bgp108.tst.md
ln -s -r ./raw/rout-bgp109.tst.md ./docs/guides/tst/rout-bgp109.tst.md
ln -s -r ./raw/rout-bgp110.tst.md ./docs/guides/tst/rout-bgp110.tst.md
ln -s -r ./raw/rout-bgp111.tst.md ./docs/guides/tst/rout-bgp111.tst.md
ln -s -r ./raw/rout-bgp112.tst.md ./docs/guides/tst/rout-bgp112.tst.md
ln -s -r ./raw/rout-bgp113.tst.md ./docs/guides/tst/rout-bgp113.tst.md
ln -s -r ./raw/rout-bgp114.tst.md ./docs/guides/tst/rout-bgp114.tst.md
ln -s -r ./raw/rout-bgp115.tst.md ./docs/guides/tst/rout-bgp115.tst.md
ln -s -r ./raw/rout-bgp116.tst.md ./docs/guides/tst/rout-bgp116.tst.md
ln -s -r ./raw/rout-bgp117.tst.md ./docs/guides/tst/rout-bgp117.tst.md
ln -s -r ./raw/rout-bgp118.tst.md ./docs/guides/tst/rout-bgp118.tst.md
ln -s -r ./raw/rout-bgp119.tst.md ./docs/guides/tst/rout-bgp119.tst.md
ln -s -r ./raw/rout-bgp120.tst.md ./docs/guides/tst/rout-bgp120.tst.md
ln -s -r ./raw/rout-bgp121.tst.md ./docs/guides/tst/rout-bgp121.tst.md
ln -s -r ./raw/rout-bgp122.tst.md ./docs/guides/tst/rout-bgp122.tst.md
ln -s -r ./raw/rout-bgp123.tst.md ./docs/guides/tst/rout-bgp123.tst.md
ln -s -r ./raw/rout-bgp124.tst.md ./docs/guides/tst/rout-bgp124.tst.md
ln -s -r ./raw/rout-bgp125.tst.md ./docs/guides/tst/rout-bgp125.tst.md
ln -s -r ./raw/rout-bgp126.tst.md ./docs/guides/tst/rout-bgp126.tst.md
ln -s -r ./raw/rout-bgp127.tst.md ./docs/guides/tst/rout-bgp127.tst.md
ln -s -r ./raw/rout-bgp128.tst.md ./docs/guides/tst/rout-bgp128.tst.md
ln -s -r ./raw/rout-bgp129.tst.md ./docs/guides/tst/rout-bgp129.tst.md
ln -s -r ./raw/rout-bgp130.tst.md ./docs/guides/tst/rout-bgp130.tst.md
ln -s -r ./raw/rout-bgp131.tst.md ./docs/guides/tst/rout-bgp131.tst.md
ln -s -r ./raw/rout-bgp132.tst.md ./docs/guides/tst/rout-bgp132.tst.md
ln -s -r ./raw/rout-bgp133.tst.md ./docs/guides/tst/rout-bgp133.tst.md
ln -s -r ./raw/rout-bgp134.tst.md ./docs/guides/tst/rout-bgp134.tst.md
ln -s -r ./raw/rout-bgp135.tst.md ./docs/guides/tst/rout-bgp135.tst.md
ln -s -r ./raw/rout-bgp136.tst.md ./docs/guides/tst/rout-bgp136.tst.md
ln -s -r ./raw/rout-bgp137.tst.md ./docs/guides/tst/rout-bgp137.tst.md
ln -s -r ./raw/rout-bgp138.tst.md ./docs/guides/tst/rout-bgp138.tst.md
ln -s -r ./raw/rout-bgp139.tst.md ./docs/guides/tst/rout-bgp139.tst.md
ln -s -r ./raw/rout-bgp140.tst.md ./docs/guides/tst/rout-bgp140.tst.md
ln -s -r ./raw/rout-bgp141.tst.md ./docs/guides/tst/rout-bgp141.tst.md
ln -s -r ./raw/rout-bgp142.tst.md ./docs/guides/tst/rout-bgp142.tst.md
ln -s -r ./raw/rout-bgp143.tst.md ./docs/guides/tst/rout-bgp143.tst.md
ln -s -r ./raw/rout-bgp144.tst.md ./docs/guides/tst/rout-bgp144.tst.md
ln -s -r ./raw/rout-bgp145.tst.md ./docs/guides/tst/rout-bgp145.tst.md
ln -s -r ./raw/rout-bgp146.tst.md ./docs/guides/tst/rout-bgp146.tst.md
ln -s -r ./raw/rout-bgp147.tst.md ./docs/guides/tst/rout-bgp147.tst.md
ln -s -r ./raw/rout-bgp148.tst.md ./docs/guides/tst/rout-bgp148.tst.md
ln -s -r ./raw/rout-bgp149.tst.md ./docs/guides/tst/rout-bgp149.tst.md
ln -s -r ./raw/rout-bgp150.tst.md ./docs/guides/tst/rout-bgp150.tst.md
ln -s -r ./raw/rout-bgp151.tst.md ./docs/guides/tst/rout-bgp151.tst.md
ln -s -r ./raw/rout-bgp152.tst.md ./docs/guides/tst/rout-bgp152.tst.md
ln -s -r ./raw/rout-bgp153.tst.md ./docs/guides/tst/rout-bgp153.tst.md
ln -s -r ./raw/rout-bgp154.tst.md ./docs/guides/tst/rout-bgp154.tst.md
ln -s -r ./raw/rout-bgp155.tst.md ./docs/guides/tst/rout-bgp155.tst.md
ln -s -r ./raw/rout-bgp156.tst.md ./docs/guides/tst/rout-bgp156.tst.md
ln -s -r ./raw/rout-bgp157.tst.md ./docs/guides/tst/rout-bgp157.tst.md
ln -s -r ./raw/rout-bgp158.tst.md ./docs/guides/tst/rout-bgp158.tst.md
ln -s -r ./raw/rout-bgp159.tst.md ./docs/guides/tst/rout-bgp159.tst.md
ln -s -r ./raw/rout-bgp160.tst.md ./docs/guides/tst/rout-bgp160.tst.md
ln -s -r ./raw/rout-bgp161.tst.md ./docs/guides/tst/rout-bgp161.tst.md
ln -s -r ./raw/rout-bgp162.tst.md ./docs/guides/tst/rout-bgp162.tst.md
ln -s -r ./raw/rout-bgp163.tst.md ./docs/guides/tst/rout-bgp163.tst.md
ln -s -r ./raw/rout-bgp164.tst.md ./docs/guides/tst/rout-bgp164.tst.md
ln -s -r ./raw/rout-bgp165.tst.md ./docs/guides/tst/rout-bgp165.tst.md
ln -s -r ./raw/rout-bgp166.tst.md ./docs/guides/tst/rout-bgp166.tst.md
ln -s -r ./raw/rout-bgp167.tst.md ./docs/guides/tst/rout-bgp167.tst.md
ln -s -r ./raw/rout-bgp168.tst.md ./docs/guides/tst/rout-bgp168.tst.md
ln -s -r ./raw/rout-bgp169.tst.md ./docs/guides/tst/rout-bgp169.tst.md
ln -s -r ./raw/rout-bgp170.tst.md ./docs/guides/tst/rout-bgp170.tst.md
ln -s -r ./raw/rout-bgp171.tst.md ./docs/guides/tst/rout-bgp171.tst.md
ln -s -r ./raw/rout-bgp172.tst.md ./docs/guides/tst/rout-bgp172.tst.md
ln -s -r ./raw/rout-bgp173.tst.md ./docs/guides/tst/rout-bgp173.tst.md
ln -s -r ./raw/rout-bgp174.tst.md ./docs/guides/tst/rout-bgp174.tst.md
ln -s -r ./raw/rout-bgp175.tst.md ./docs/guides/tst/rout-bgp175.tst.md
ln -s -r ./raw/rout-bgp176.tst.md ./docs/guides/tst/rout-bgp176.tst.md
ln -s -r ./raw/rout-bgp177.tst.md ./docs/guides/tst/rout-bgp177.tst.md
ln -s -r ./raw/rout-bgp178.tst.md ./docs/guides/tst/rout-bgp178.tst.md
ln -s -r ./raw/rout-bgp179.tst.md ./docs/guides/tst/rout-bgp179.tst.md
ln -s -r ./raw/rout-bgp180.tst.md ./docs/guides/tst/rout-bgp180.tst.md
ln -s -r ./raw/rout-bgp181.tst.md ./docs/guides/tst/rout-bgp181.tst.md
ln -s -r ./raw/rout-bgp182.tst.md ./docs/guides/tst/rout-bgp182.tst.md
ln -s -r ./raw/rout-bgp183.tst.md ./docs/guides/tst/rout-bgp183.tst.md
ln -s -r ./raw/rout-bgp184.tst.md ./docs/guides/tst/rout-bgp184.tst.md
ln -s -r ./raw/rout-bgp185.tst.md ./docs/guides/tst/rout-bgp185.tst.md
ln -s -r ./raw/rout-bgp186.tst.md ./docs/guides/tst/rout-bgp186.tst.md
ln -s -r ./raw/rout-bgp187.tst.md ./docs/guides/tst/rout-bgp187.tst.md
ln -s -r ./raw/rout-bgp188.tst.md ./docs/guides/tst/rout-bgp188.tst.md
ln -s -r ./raw/rout-bgp189.tst.md ./docs/guides/tst/rout-bgp189.tst.md
ln -s -r ./raw/rout-bgp190.tst.md ./docs/guides/tst/rout-bgp190.tst.md
ln -s -r ./raw/rout-bgp191.tst.md ./docs/guides/tst/rout-bgp191.tst.md
ln -s -r ./raw/rout-bgp192.tst.md ./docs/guides/tst/rout-bgp192.tst.md
ln -s -r ./raw/rout-bgp193.tst.md ./docs/guides/tst/rout-bgp193.tst.md
ln -s -r ./raw/rout-bgp194.tst.md ./docs/guides/tst/rout-bgp194.tst.md
ln -s -r ./raw/rout-bgp195.tst.md ./docs/guides/tst/rout-bgp195.tst.md
ln -s -r ./raw/rout-bgp196.tst.md ./docs/guides/tst/rout-bgp196.tst.md
ln -s -r ./raw/rout-bgp197.tst.md ./docs/guides/tst/rout-bgp197.tst.md
ln -s -r ./raw/rout-bgp198.tst.md ./docs/guides/tst/rout-bgp198.tst.md
ln -s -r ./raw/rout-bgp199.tst.md ./docs/guides/tst/rout-bgp199.tst.md
ln -s -r ./raw/rout-bgp200.tst.md ./docs/guides/tst/rout-bgp200.tst.md
ln -s -r ./raw/rout-bgp201.tst.md ./docs/guides/tst/rout-bgp201.tst.md
ln -s -r ./raw/rout-bgp202.tst.md ./docs/guides/tst/rout-bgp202.tst.md
ln -s -r ./raw/rout-bgp203.tst.md ./docs/guides/tst/rout-bgp203.tst.md
ln -s -r ./raw/rout-bgp204.tst.md ./docs/guides/tst/rout-bgp204.tst.md
ln -s -r ./raw/rout-bgp205.tst.md ./docs/guides/tst/rout-bgp205.tst.md
ln -s -r ./raw/rout-bgp206.tst.md ./docs/guides/tst/rout-bgp206.tst.md
ln -s -r ./raw/rout-bgp207.tst.md ./docs/guides/tst/rout-bgp207.tst.md
ln -s -r ./raw/rout-bgp208.tst.md ./docs/guides/tst/rout-bgp208.tst.md
ln -s -r ./raw/rout-bgp209.tst.md ./docs/guides/tst/rout-bgp209.tst.md
ln -s -r ./raw/rout-bgp210.tst.md ./docs/guides/tst/rout-bgp210.tst.md
ln -s -r ./raw/rout-bgp211.tst.md ./docs/guides/tst/rout-bgp211.tst.md
ln -s -r ./raw/rout-bgp212.tst.md ./docs/guides/tst/rout-bgp212.tst.md
ln -s -r ./raw/rout-bgp213.tst.md ./docs/guides/tst/rout-bgp213.tst.md
ln -s -r ./raw/rout-bgp214.tst.md ./docs/guides/tst/rout-bgp214.tst.md
ln -s -r ./raw/rout-bgp215.tst.md ./docs/guides/tst/rout-bgp215.tst.md
ln -s -r ./raw/rout-bgp216.tst.md ./docs/guides/tst/rout-bgp216.tst.md
ln -s -r ./raw/rout-bgp217.tst.md ./docs/guides/tst/rout-bgp217.tst.md
ln -s -r ./raw/rout-bgp218.tst.md ./docs/guides/tst/rout-bgp218.tst.md
ln -s -r ./raw/rout-bgp219.tst.md ./docs/guides/tst/rout-bgp219.tst.md
ln -s -r ./raw/rout-bgp220.tst.md ./docs/guides/tst/rout-bgp220.tst.md
ln -s -r ./raw/rout-bgp221.tst.md ./docs/guides/tst/rout-bgp221.tst.md
ln -s -r ./raw/rout-bgp222.tst.md ./docs/guides/tst/rout-bgp222.tst.md
ln -s -r ./raw/rout-bgp223.tst.md ./docs/guides/tst/rout-bgp223.tst.md
ln -s -r ./raw/rout-bgp224.tst.md ./docs/guides/tst/rout-bgp224.tst.md
ln -s -r ./raw/rout-bgp225.tst.md ./docs/guides/tst/rout-bgp225.tst.md
ln -s -r ./raw/rout-bgp226.tst.md ./docs/guides/tst/rout-bgp226.tst.md
ln -s -r ./raw/rout-bgp227.tst.md ./docs/guides/tst/rout-bgp227.tst.md
ln -s -r ./raw/rout-bgp228.tst.md ./docs/guides/tst/rout-bgp228.tst.md
ln -s -r ./raw/rout-bgp229.tst.md ./docs/guides/tst/rout-bgp229.tst.md
ln -s -r ./raw/rout-bgp230.tst.md ./docs/guides/tst/rout-bgp230.tst.md
ln -s -r ./raw/rout-bgp231.tst.md ./docs/guides/tst/rout-bgp231.tst.md
ln -s -r ./raw/rout-bgp232.tst.md ./docs/guides/tst/rout-bgp232.tst.md
ln -s -r ./raw/rout-bgp233.tst.md ./docs/guides/tst/rout-bgp233.tst.md
ln -s -r ./raw/rout-bgp234.tst.md ./docs/guides/tst/rout-bgp234.tst.md
ln -s -r ./raw/rout-bgp235.tst.md ./docs/guides/tst/rout-bgp235.tst.md
ln -s -r ./raw/rout-bgp236.tst.md ./docs/guides/tst/rout-bgp236.tst.md
ln -s -r ./raw/rout-bgp237.tst.md ./docs/guides/tst/rout-bgp237.tst.md
ln -s -r ./raw/rout-bgp238.tst.md ./docs/guides/tst/rout-bgp238.tst.md
ln -s -r ./raw/rout-bgp239.tst.md ./docs/guides/tst/rout-bgp239.tst.md
ln -s -r ./raw/rout-bgp240.tst.md ./docs/guides/tst/rout-bgp240.tst.md
ln -s -r ./raw/rout-bgp241.tst.md ./docs/guides/tst/rout-bgp241.tst.md
ln -s -r ./raw/rout-bgp242.tst.md ./docs/guides/tst/rout-bgp242.tst.md
ln -s -r ./raw/rout-bgp243.tst.md ./docs/guides/tst/rout-bgp243.tst.md
ln -s -r ./raw/rout-bgp244.tst.md ./docs/guides/tst/rout-bgp244.tst.md
ln -s -r ./raw/rout-bgp245.tst.md ./docs/guides/tst/rout-bgp245.tst.md
ln -s -r ./raw/rout-bgp246.tst.md ./docs/guides/tst/rout-bgp246.tst.md
ln -s -r ./raw/rout-bgp247.tst.md ./docs/guides/tst/rout-bgp247.tst.md
ln -s -r ./raw/rout-bgp248.tst.md ./docs/guides/tst/rout-bgp248.tst.md
ln -s -r ./raw/rout-bgp249.tst.md ./docs/guides/tst/rout-bgp249.tst.md
ln -s -r ./raw/rout-bgp250.tst.md ./docs/guides/tst/rout-bgp250.tst.md
ln -s -r ./raw/rout-bgp251.tst.md ./docs/guides/tst/rout-bgp251.tst.md
ln -s -r ./raw/rout-bgp252.tst.md ./docs/guides/tst/rout-bgp252.tst.md
ln -s -r ./raw/rout-bgp253.tst.md ./docs/guides/tst/rout-bgp253.tst.md
ln -s -r ./raw/rout-bgp254.tst.md ./docs/guides/tst/rout-bgp254.tst.md
ln -s -r ./raw/rout-bgp255.tst.md ./docs/guides/tst/rout-bgp255.tst.md
ln -s -r ./raw/rout-bgp256.tst.md ./docs/guides/tst/rout-bgp256.tst.md
ln -s -r ./raw/rout-bgp257.tst.md ./docs/guides/tst/rout-bgp257.tst.md
ln -s -r ./raw/rout-bgp258.tst.md ./docs/guides/tst/rout-bgp258.tst.md
ln -s -r ./raw/rout-bgp259.tst.md ./docs/guides/tst/rout-bgp259.tst.md
ln -s -r ./raw/rout-bgp260.tst.md ./docs/guides/tst/rout-bgp260.tst.md
ln -s -r ./raw/rout-bgp261.tst.md ./docs/guides/tst/rout-bgp261.tst.md
ln -s -r ./raw/rout-bgp262.tst.md ./docs/guides/tst/rout-bgp262.tst.md
ln -s -r ./raw/rout-bgp263.tst.md ./docs/guides/tst/rout-bgp263.tst.md
ln -s -r ./raw/rout-bgp264.tst.md ./docs/guides/tst/rout-bgp264.tst.md
ln -s -r ./raw/rout-bgp265.tst.md ./docs/guides/tst/rout-bgp265.tst.md
ln -s -r ./raw/rout-bgp266.tst.md ./docs/guides/tst/rout-bgp266.tst.md
ln -s -r ./raw/rout-bgp267.tst.md ./docs/guides/tst/rout-bgp267.tst.md
ln -s -r ./raw/rout-bgp268.tst.md ./docs/guides/tst/rout-bgp268.tst.md
ln -s -r ./raw/rout-bgp269.tst.md ./docs/guides/tst/rout-bgp269.tst.md
ln -s -r ./raw/rout-bgp270.tst.md ./docs/guides/tst/rout-bgp270.tst.md
ln -s -r ./raw/rout-bgp271.tst.md ./docs/guides/tst/rout-bgp271.tst.md
ln -s -r ./raw/rout-bgp272.tst.md ./docs/guides/tst/rout-bgp272.tst.md
ln -s -r ./raw/rout-bgp273.tst.md ./docs/guides/tst/rout-bgp273.tst.md
ln -s -r ./raw/rout-bgp274.tst.md ./docs/guides/tst/rout-bgp274.tst.md
ln -s -r ./raw/rout-bgp275.tst.md ./docs/guides/tst/rout-bgp275.tst.md
ln -s -r ./raw/rout-bgp276.tst.md ./docs/guides/tst/rout-bgp276.tst.md
ln -s -r ./raw/rout-bgp277.tst.md ./docs/guides/tst/rout-bgp277.tst.md
ln -s -r ./raw/rout-bgp278.tst.md ./docs/guides/tst/rout-bgp278.tst.md
ln -s -r ./raw/rout-bgp279.tst.md ./docs/guides/tst/rout-bgp279.tst.md
ln -s -r ./raw/rout-bgp280.tst.md ./docs/guides/tst/rout-bgp280.tst.md
ln -s -r ./raw/rout-bgp281.tst.md ./docs/guides/tst/rout-bgp281.tst.md
ln -s -r ./raw/rout-bgp282.tst.md ./docs/guides/tst/rout-bgp282.tst.md
ln -s -r ./raw/rout-bgp283.tst.md ./docs/guides/tst/rout-bgp283.tst.md
ln -s -r ./raw/rout-bgp284.tst.md ./docs/guides/tst/rout-bgp284.tst.md
ln -s -r ./raw/rout-bgp285.tst.md ./docs/guides/tst/rout-bgp285.tst.md
ln -s -r ./raw/rout-bgp286.tst.md ./docs/guides/tst/rout-bgp286.tst.md
ln -s -r ./raw/rout-bgp287.tst.md ./docs/guides/tst/rout-bgp287.tst.md
ln -s -r ./raw/rout-bgp288.tst.md ./docs/guides/tst/rout-bgp288.tst.md
ln -s -r ./raw/rout-bgp289.tst.md ./docs/guides/tst/rout-bgp289.tst.md
ln -s -r ./raw/rout-bgp290.tst.md ./docs/guides/tst/rout-bgp290.tst.md
ln -s -r ./raw/rout-bgp291.tst.md ./docs/guides/tst/rout-bgp291.tst.md
ln -s -r ./raw/rout-bgp292.tst.md ./docs/guides/tst/rout-bgp292.tst.md
ln -s -r ./raw/rout-bgp293.tst.md ./docs/guides/tst/rout-bgp293.tst.md
ln -s -r ./raw/rout-bgp294.tst.md ./docs/guides/tst/rout-bgp294.tst.md
ln -s -r ./raw/rout-bgp295.tst.md ./docs/guides/tst/rout-bgp295.tst.md
ln -s -r ./raw/rout-bgp296.tst.md ./docs/guides/tst/rout-bgp296.tst.md
ln -s -r ./raw/rout-bgp297.tst.md ./docs/guides/tst/rout-bgp297.tst.md
ln -s -r ./raw/rout-bgp298.tst.md ./docs/guides/tst/rout-bgp298.tst.md
ln -s -r ./raw/rout-bgp299.tst.md ./docs/guides/tst/rout-bgp299.tst.md
ln -s -r ./raw/rout-bgp300.tst.md ./docs/guides/tst/rout-bgp300.tst.md
ln -s -r ./raw/rout-bgp301.tst.md ./docs/guides/tst/rout-bgp301.tst.md
ln -s -r ./raw/rout-bgp302.tst.md ./docs/guides/tst/rout-bgp302.tst.md
ln -s -r ./raw/rout-bgp303.tst.md ./docs/guides/tst/rout-bgp303.tst.md
ln -s -r ./raw/rout-bgp304.tst.md ./docs/guides/tst/rout-bgp304.tst.md
ln -s -r ./raw/rout-bgp305.tst.md ./docs/guides/tst/rout-bgp305.tst.md
ln -s -r ./raw/rout-bgp306.tst.md ./docs/guides/tst/rout-bgp306.tst.md
ln -s -r ./raw/rout-bgp307.tst.md ./docs/guides/tst/rout-bgp307.tst.md
ln -s -r ./raw/rout-bgp308.tst.md ./docs/guides/tst/rout-bgp308.tst.md
ln -s -r ./raw/rout-bgp309.tst.md ./docs/guides/tst/rout-bgp309.tst.md
ln -s -r ./raw/rout-bgp310.tst.md ./docs/guides/tst/rout-bgp310.tst.md
ln -s -r ./raw/rout-bgp311.tst.md ./docs/guides/tst/rout-bgp311.tst.md
ln -s -r ./raw/rout-bgp312.tst.md ./docs/guides/tst/rout-bgp312.tst.md
ln -s -r ./raw/rout-bgp313.tst.md ./docs/guides/tst/rout-bgp313.tst.md
ln -s -r ./raw/rout-bgp314.tst.md ./docs/guides/tst/rout-bgp314.tst.md
ln -s -r ./raw/rout-bgp315.tst.md ./docs/guides/tst/rout-bgp315.tst.md
ln -s -r ./raw/rout-bgp316.tst.md ./docs/guides/tst/rout-bgp316.tst.md
ln -s -r ./raw/rout-bgp317.tst.md ./docs/guides/tst/rout-bgp317.tst.md
ln -s -r ./raw/rout-bgp318.tst.md ./docs/guides/tst/rout-bgp318.tst.md
ln -s -r ./raw/rout-bgp319.tst.md ./docs/guides/tst/rout-bgp319.tst.md
ln -s -r ./raw/rout-bgp320.tst.md ./docs/guides/tst/rout-bgp320.tst.md
ln -s -r ./raw/rout-bgp321.tst.md ./docs/guides/tst/rout-bgp321.tst.md
ln -s -r ./raw/rout-bgp322.tst.md ./docs/guides/tst/rout-bgp322.tst.md
ln -s -r ./raw/rout-bgp323.tst.md ./docs/guides/tst/rout-bgp323.tst.md
ln -s -r ./raw/rout-bgp324.tst.md ./docs/guides/tst/rout-bgp324.tst.md
ln -s -r ./raw/rout-bgp325.tst.md ./docs/guides/tst/rout-bgp325.tst.md
ln -s -r ./raw/rout-bgp326.tst.md ./docs/guides/tst/rout-bgp326.tst.md
ln -s -r ./raw/rout-bgp327.tst.md ./docs/guides/tst/rout-bgp327.tst.md
ln -s -r ./raw/rout-bgp328.tst.md ./docs/guides/tst/rout-bgp328.tst.md
ln -s -r ./raw/rout-bgp329.tst.md ./docs/guides/tst/rout-bgp329.tst.md
ln -s -r ./raw/rout-bgp330.tst.md ./docs/guides/tst/rout-bgp330.tst.md
ln -s -r ./raw/rout-bgp331.tst.md ./docs/guides/tst/rout-bgp331.tst.md
ln -s -r ./raw/rout-bgp332.tst.md ./docs/guides/tst/rout-bgp332.tst.md
ln -s -r ./raw/rout-bgp333.tst.md ./docs/guides/tst/rout-bgp333.tst.md
ln -s -r ./raw/rout-bgp334.tst.md ./docs/guides/tst/rout-bgp334.tst.md
ln -s -r ./raw/rout-bgp335.tst.md ./docs/guides/tst/rout-bgp335.tst.md
ln -s -r ./raw/rout-bgp336.tst.md ./docs/guides/tst/rout-bgp336.tst.md
ln -s -r ./raw/rout-bgp337.tst.md ./docs/guides/tst/rout-bgp337.tst.md
ln -s -r ./raw/rout-bgp338.tst.md ./docs/guides/tst/rout-bgp338.tst.md
ln -s -r ./raw/rout-bgp339.tst.md ./docs/guides/tst/rout-bgp339.tst.md
ln -s -r ./raw/rout-bgp340.tst.md ./docs/guides/tst/rout-bgp340.tst.md
ln -s -r ./raw/rout-bgp341.tst.md ./docs/guides/tst/rout-bgp341.tst.md
ln -s -r ./raw/rout-bgp342.tst.md ./docs/guides/tst/rout-bgp342.tst.md
ln -s -r ./raw/rout-bgp343.tst.md ./docs/guides/tst/rout-bgp343.tst.md
ln -s -r ./raw/rout-bgp344.tst.md ./docs/guides/tst/rout-bgp344.tst.md
ln -s -r ./raw/rout-bgp345.tst.md ./docs/guides/tst/rout-bgp345.tst.md
ln -s -r ./raw/rout-bgp346.tst.md ./docs/guides/tst/rout-bgp346.tst.md
ln -s -r ./raw/rout-bgp347.tst.md ./docs/guides/tst/rout-bgp347.tst.md
ln -s -r ./raw/rout-bgp348.tst.md ./docs/guides/tst/rout-bgp348.tst.md
ln -s -r ./raw/rout-bgp349.tst.md ./docs/guides/tst/rout-bgp349.tst.md
ln -s -r ./raw/rout-bgp350.tst.md ./docs/guides/tst/rout-bgp350.tst.md
ln -s -r ./raw/rout-bgp351.tst.md ./docs/guides/tst/rout-bgp351.tst.md
ln -s -r ./raw/rout-bgp352.tst.md ./docs/guides/tst/rout-bgp352.tst.md
ln -s -r ./raw/rout-bgp353.tst.md ./docs/guides/tst/rout-bgp353.tst.md
ln -s -r ./raw/rout-bgp354.tst.md ./docs/guides/tst/rout-bgp354.tst.md
ln -s -r ./raw/rout-bgp355.tst.md ./docs/guides/tst/rout-bgp355.tst.md
ln -s -r ./raw/rout-bgp356.tst.md ./docs/guides/tst/rout-bgp356.tst.md
ln -s -r ./raw/rout-bgp357.tst.md ./docs/guides/tst/rout-bgp357.tst.md
ln -s -r ./raw/rout-bgp358.tst.md ./docs/guides/tst/rout-bgp358.tst.md
ln -s -r ./raw/rout-bgp359.tst.md ./docs/guides/tst/rout-bgp359.tst.md
ln -s -r ./raw/rout-bgp360.tst.md ./docs/guides/tst/rout-bgp360.tst.md
ln -s -r ./raw/rout-bgp361.tst.md ./docs/guides/tst/rout-bgp361.tst.md
ln -s -r ./raw/rout-bgp362.tst.md ./docs/guides/tst/rout-bgp362.tst.md
ln -s -r ./raw/rout-bgp363.tst.md ./docs/guides/tst/rout-bgp363.tst.md
ln -s -r ./raw/rout-bgp364.tst.md ./docs/guides/tst/rout-bgp364.tst.md
ln -s -r ./raw/rout-bgp365.tst.md ./docs/guides/tst/rout-bgp365.tst.md
ln -s -r ./raw/rout-bgp366.tst.md ./docs/guides/tst/rout-bgp366.tst.md
ln -s -r ./raw/rout-bgp367.tst.md ./docs/guides/tst/rout-bgp367.tst.md
ln -s -r ./raw/rout-bgp368.tst.md ./docs/guides/tst/rout-bgp368.tst.md
ln -s -r ./raw/rout-bgp369.tst.md ./docs/guides/tst/rout-bgp369.tst.md
ln -s -r ./raw/rout-bgp370.tst.md ./docs/guides/tst/rout-bgp370.tst.md
ln -s -r ./raw/rout-bgp371.tst.md ./docs/guides/tst/rout-bgp371.tst.md
ln -s -r ./raw/rout-bgp372.tst.md ./docs/guides/tst/rout-bgp372.tst.md
ln -s -r ./raw/rout-bgp373.tst.md ./docs/guides/tst/rout-bgp373.tst.md
ln -s -r ./raw/rout-bgp374.tst.md ./docs/guides/tst/rout-bgp374.tst.md
ln -s -r ./raw/rout-bgp375.tst.md ./docs/guides/tst/rout-bgp375.tst.md
ln -s -r ./raw/rout-bgp376.tst.md ./docs/guides/tst/rout-bgp376.tst.md
ln -s -r ./raw/rout-bgp377.tst.md ./docs/guides/tst/rout-bgp377.tst.md
ln -s -r ./raw/rout-bgp378.tst.md ./docs/guides/tst/rout-bgp378.tst.md
ln -s -r ./raw/rout-bgp379.tst.md ./docs/guides/tst/rout-bgp379.tst.md
ln -s -r ./raw/rout-bgp380.tst.md ./docs/guides/tst/rout-bgp380.tst.md
ln -s -r ./raw/rout-bgp381.tst.md ./docs/guides/tst/rout-bgp381.tst.md
ln -s -r ./raw/rout-bgp382.tst.md ./docs/guides/tst/rout-bgp382.tst.md
ln -s -r ./raw/rout-bgp383.tst.md ./docs/guides/tst/rout-bgp383.tst.md
ln -s -r ./raw/rout-bgp384.tst.md ./docs/guides/tst/rout-bgp384.tst.md
ln -s -r ./raw/rout-bgp385.tst.md ./docs/guides/tst/rout-bgp385.tst.md
ln -s -r ./raw/rout-bgp386.tst.md ./docs/guides/tst/rout-bgp386.tst.md
ln -s -r ./raw/rout-bgp387.tst.md ./docs/guides/tst/rout-bgp387.tst.md
ln -s -r ./raw/rout-bgp388.tst.md ./docs/guides/tst/rout-bgp388.tst.md
ln -s -r ./raw/rout-bgp389.tst.md ./docs/guides/tst/rout-bgp389.tst.md
ln -s -r ./raw/rout-bgp390.tst.md ./docs/guides/tst/rout-bgp390.tst.md
ln -s -r ./raw/rout-bgp391.tst.md ./docs/guides/tst/rout-bgp391.tst.md
ln -s -r ./raw/rout-bgp392.tst.md ./docs/guides/tst/rout-bgp392.tst.md
ln -s -r ./raw/rout-bgp393.tst.md ./docs/guides/tst/rout-bgp393.tst.md
ln -s -r ./raw/rout-bgp394.tst.md ./docs/guides/tst/rout-bgp394.tst.md
ln -s -r ./raw/rout-bgp395.tst.md ./docs/guides/tst/rout-bgp395.tst.md
ln -s -r ./raw/rout-bgp396.tst.md ./docs/guides/tst/rout-bgp396.tst.md
ln -s -r ./raw/rout-bgp397.tst.md ./docs/guides/tst/rout-bgp397.tst.md

# gre
ln -s -r ./raw/conn-gre01.tst.md ./docs/guides/tst/conn-gre01.tst.md
ln -s -r ./raw/conn-gre02.tst.md ./docs/guides/tst/conn-gre02.tst.md
ln -s -r ./raw/conn-gre03.tst.md ./docs/guides/tst/conn-gre03.tst.md
ln -s -r ./raw/conn-gre04.tst.md ./docs/guides/tst/conn-gre04.tst.md
ln -s -r ./raw/conn-gre05.tst.md ./docs/guides/tst/conn-gre05.tst.md
ln -s -r ./raw/conn-gre06.tst.md ./docs/guides/tst/conn-gre06.tst.md
ln -s -r ./raw/conn-gre07.tst.md ./docs/guides/tst/conn-gre07.tst.md
ln -s -r ./raw/conn-gre08.tst.md ./docs/guides/tst/conn-gre08.tst.md
ln -s -r ./raw/conn-gre09.tst.md ./docs/guides/tst/conn-gre09.tst.md
ln -s -r ./raw/conn-gre10.tst.md ./docs/guides/tst/conn-gre10.tst.md
ln -s -r ./raw/conn-gre11.tst.md ./docs/guides/tst/conn-gre11.tst.md
ln -s -r ./raw/conn-gre12.tst.md ./docs/guides/tst/conn-gre12.tst.md

# telnet
ln -s -r ./raw/conn-telnet01.tst.md ./docs/guides/tst/conn-telnet01.tst.md
ln -s -r ./raw/conn-telnet02.tst.md ./docs/guides/tst/conn-telnet02.tst.md

# ssh
ln -s -r ./raw/crypt-ssh.tst.md ./docs/guides/tst/crypt-ssh.tst.md
ln -s -r ./raw/intop1-ssh.tst.md ./docs/guides/tst/intop1-ssh.tst.md

# eigrp
ln -s -r ./raw/intop1-eigrp01.tst.md ./docs/guides/tst/intop1-eigrp01.tst.md
ln -s -r ./raw/intop1-eigrp02.tst.md ./docs/guides/tst/intop1-eigrp02.tst.md
ln -s -r ./raw/intop2-eigrp01.tst.md ./docs/guides/tst/intop2-eigrp01.tst.md
ln -s -r ./raw/intop2-eigrp02.tst.md ./docs/guides/tst/intop2-eigrp02.tst.md
ln -s -r ./raw/rout-eigrp01.tst.md ./docs/guides/tst/rout-eigrp01.tst.md
ln -s -r ./raw/rout-eigrp02.tst.md ./docs/guides/tst/rout-eigrp02.tst.md
ln -s -r ./raw/rout-eigrp03.tst.md ./docs/guides/tst/rout-eigrp03.tst.md
ln -s -r ./raw/rout-eigrp04.tst.md ./docs/guides/tst/rout-eigrp04.tst.md
ln -s -r ./raw/rout-eigrp05.tst.md ./docs/guides/tst/rout-eigrp05.tst.md
ln -s -r ./raw/rout-eigrp06.tst.md ./docs/guides/tst/rout-eigrp06.tst.md
ln -s -r ./raw/rout-eigrp07.tst.md ./docs/guides/tst/rout-eigrp07.tst.md
ln -s -r ./raw/rout-eigrp08.tst.md ./docs/guides/tst/rout-eigrp08.tst.md
ln -s -r ./raw/rout-eigrp09.tst.md ./docs/guides/tst/rout-eigrp09.tst.md
ln -s -r ./raw/rout-eigrp10.tst.md ./docs/guides/tst/rout-eigrp10.tst.md
ln -s -r ./raw/rout-eigrp11.tst.md ./docs/guides/tst/rout-eigrp11.tst.md
ln -s -r ./raw/rout-eigrp12.tst.md ./docs/guides/tst/rout-eigrp12.tst.md
ln -s -r ./raw/rout-eigrp13.tst.md ./docs/guides/tst/rout-eigrp13.tst.md
ln -s -r ./raw/rout-eigrp14.tst.md ./docs/guides/tst/rout-eigrp14.tst.md
ln -s -r ./raw/rout-eigrp15.tst.md ./docs/guides/tst/rout-eigrp15.tst.md
ln -s -r ./raw/rout-eigrp16.tst.md ./docs/guides/tst/rout-eigrp16.tst.md
ln -s -r ./raw/rout-eigrp17.tst.md ./docs/guides/tst/rout-eigrp17.tst.md
ln -s -r ./raw/rout-eigrp18.tst.md ./docs/guides/tst/rout-eigrp18.tst.md
ln -s -r ./raw/rout-eigrp19.tst.md ./docs/guides/tst/rout-eigrp19.tst.md
ln -s -r ./raw/rout-eigrp20.tst.md ./docs/guides/tst/rout-eigrp20.tst.md
ln -s -r ./raw/rout-eigrp21.tst.md ./docs/guides/tst/rout-eigrp21.tst.md
ln -s -r ./raw/rout-redist08.tst.md ./docs/guides/tst/rout-redist08.tst.md

